# Configuration for the-welcome-bot - https://github.com/bash-bot/the-welcome-bot

# Message for a new user who open an issue
issueOpen: >
  Thanks and congrats for opening your very first issue in this project.
  You may submit a PR on the same if you like!
  Hope you have a great time here :)

# Message for a new user who opens a PR
prOpen: >
  Thank you and congrats for your first PR on this project.
  We will review it soon!
  Till then you can checkout the README for more details.
  Hope you have a great time here :)

# Default message for a new user
welcomeMessage: >
  Hello World! Welcome to the project! Feel free to explore it.
  Checkout the README for more details on it.
  Want to contribute? Make an issue or submit a PR.
  Hope you have a great time here :)
