name: Node CI


on:
  pull_request:
    branches:
      - develop

jobs:
  validate-pr:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8']
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup environment
        run: |
          npm install -g yarn
          yarn install
      - name: Run unit tests
        run: |
          yarn run test:unit
      - name: Run e2e tests
        run: |
          yarn run test:integration
        env:
          CI: true

